routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ColorsController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\ProducBrandController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\UnitController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    
    Route::resource('customer', CustomerController::class);
    Route::get('uncategorized', [CategoryController::class, 'uncategorized']);
    Route::resource('category', CategoryController::class);
    Route::resource('sub_category', SubCategoryController::class);
    Route::resource('product_brand', ProducBrandController::class);
    Route::resource('unit', UnitController::class);
    Route::resource('colors', ColorsController::class);
    Route::resource('size', SizeController::class);
    Route::resource('product', ProductController::class);
    Route::get('get_sub_category', [SubCategoryController::class, 'get_sub_category']);
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table = 'customers';
    protected $primaryKey = 'id';
    protected $fillable = ['name', 'email', 'address', 'phone', 'image', 'password', 'status'];
    use HasFactory;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Customer;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = array(
            'page_name' => 'Customer',
            'customers' => Customer::all(),
        );
        return view('customer.index')->with('data' , $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data = array(
            'page_name' => 'Create New Customer',
        );
        return view('customer.create')->with('data' , $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {        
        $input = $request->all();
        request()->validate([
            'name' => 'required|max:20|min:3|regex:/^[A-Za-z_-]/',
            'email' => 'required|email|min:5|max:100|unique:customer',            
            'phone' => 'required|max:50',            
            'password' => 'required|min:5|max:50',
            'address' => 'required|min:5|max:50',
        ]);

        $input['password'] = Hash::make($input['password']);
        
        if(isset($input['image'])){            
            $file_name = time().$request->file('image')->getClientOriginalName();
            $request->file('image')->storeAs('image', $file_name, 'public');
            $input['image'] = $file_name;
        }else{
            $input['image'] = '';
        }

        unset($input['_token']);
        Customer::create($input);        
        return redirect('customer')->with('flash_message' , "Customer Added");
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $data = array(
            'page_name' => 'Customer Profile',
            'customers' => Customer::find($id),
        );
        

        return view('customer.show')->with('data', $data);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        echo "edit";die;
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {        
        $customer = Customer::find($id);
        $input = $request->all();


        if (array_key_exists("current_password",$input)){
            
            $user = Customer::find($input['id']);            

            # Validation
            $request->validate([
                'current_password' => 'required',
                'new_password' => 'required|confirmed|',
                'new_password_confirmation' => 'required|same:new_password|different:current_password',
            ]);

            #Match The Old Password
            if(Hash::check($input['current_password'], $user['password'])){
                
                $new_password['password'] = Hash::make($input['new_password']);
                $customer->update($new_password);
                return redirect('customer')->with('flash_message', 'Password has been changed');
            }else{
                return redirect('customer')->with('flash_message', 'Password current password not correct');
            }

        }


        if(isset($input['image'])){            
            $file_name = time().$request->file('image')->getClientOriginalName();
            $request->file('image')->storeAs('image', $file_name, 'public');
            $input['image'] = $file_name;
            Storage::disk('public')->delete('image/category' . $input['old_img']);
        }

        //echo '<pre>';print_r($input);echo '</pre>';die;

        request()->validate([
            'name' => 'required|max:20|min:3|regex:/^[A-Za-z_-]/',
            'email' => Rule::unique('customer')->ignore($id),
            'phone' => 'required|max:50',
            'address' => 'required|min:5|max:50',
            'status' => 'required',
        ]);

        unset($input['password']);

        $customer->update($input);
        return redirect('customer')->with('flash_message', 'Updated');
        
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $customer = Customer::find($id);
        Storage::disk('public')->delete('image/' . $customer['image']);
        Customer::destroy($id);
        return redirect('customer')->with('del_message', 'Deleted!');
    }
}

resources/views/customer/create.blade.php
@extends('customer.layout')
@section('content')
<main id="main" class="main">
    <div class="pagetitle">
        <h1><?= $data['page_name']; ?></h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active"><?= $data['page_name']; ?></li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    
    <section class="section dashboard">
        <div class="row">

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Add New</h5>
                        
                        <form class="row g-3" action="{{ route('customer.store') }}" method="post" enctype="multipart/form-data">
                            {!! csrf_field() !!}
                            <div class="col-12">
                                <label for="inputNanme4" class="form-label">Your Name</label>
                                <input type="text" value="{{ old('name') }}" name="name" class="form-control" id="inputNanme4">
                                <b><small class="text-danger">{{ $errors->first('name') }}</small></b>
                            </div>
                            <div class="col-12">
                                <label for="inputEmail4" class="form-label">Email</label>
                                <input type="text" value="{{ old('email') }}" name="email" class="form-control" id="inputEmail4">
                                <b><small class="text-danger">{{ $errors->first('email') }}</small></b>
                            </div>
                            <div class="col-12">
                                <label for="phone" class="form-label">Phone</label>
                                <input type="text" value="{{ old('phone') }}" name="phone" class="form-control" id="phone">
                                <b><small class="text-danger">{{ $errors->first('phone') }}</small></b>
                            </div>
                            <div class="col-12">
                                <label for="inputPassword4" class="form-label">Password</label>
                                <input type="password" value="{{ old('password') }}" name="password" class="form-control" id="inputPassword4">
                                <b><small class="text-danger">{{ $errors->first('password') }}</small></b>
                            </div>
                            <div class="col-12">
                                <label for="inputAddress" class="form-label">Address</label>
                                <input type="text" value="{{ old('address') }}" name="address" class="form-control" id="inputAddress" placeholder="1234 Main St">
                                <b><small class="text-danger">{{ $errors->first('address') }}</small></b>
                            </div>
                            <div class="col-12">
                                <label for="image" class="form-label">Photo</label>
                                <input type="file" name="image" class="form-control" id="inputAddress" placeholder="1234 Main St">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <button type="reset" class="btn btn-secondary">Reset</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>
    </section>
</main>
@endsection

resources/views/customer/index.blade.php
@extends('customer.layout')
@section('content')
<main id="main" class="main">

    <div class="pagetitle">
        @if(Session::has('flash_message'))
        <br><br>
        <div class="alert alert-success">
            <h5>{{ Session::get('flash_message') }}</h5>
        </div>
        @endif

        @if(Session::has('del_message'))
        <br><br>
        <div class="alert alert-danger">
            <h5>{{ Session::get('del_message') }}</h5>
        </div>
        @endif
        <h1><?= $data['page_name']; ?></h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active"><?= $data['page_name']; ?></li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">All</h5>

                        <!-- Default Table -->
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Address</th>
                                    <th scope="col">Phone</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach($data['customers'] as $item)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>{{ $item->address }}</td>
                                    <td>{{ $item->phone }}</td>
                                    <td>
                                        @if($item->status == 1)
                                            Active
                                        @else
                                            Inactive
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ url('/customer/'. $item->id)}}"><button class="btn btn-sm btn-success">View</button></a>
                                        <!-- <a href="{{ url('/customer/'. $item->id .'/edit')}}"><button class="btn btn-sm btn-primary">Edit</button></a> -->
                                        <form method="POST" action="{{ url('/customer' . '/' . $item->id) }}" accept-charset="UTF-8" style="display:inline">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Student" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                        <!-- End Default Table Example -->
                    </div>
                </div>
            </div>

        </div>
    </section>
</main>
@endsection

resources/views/customer/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{asset('assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/bootstrap-icons/bootstrap-icons.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/quill/quill.snow.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/quill/quill.bubble.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
    <link href="{{asset('assets/vendor/simple-datatables/style.css')}}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- Template Main CSS File -->
    <link href="{{asset('assets/css/style.css')}}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: Nov 17 2023 with Bootstrap v5.3.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <!-- ======= Header ======= -->
    @livewire('navigation-menu')
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="/dashboard">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#cutomer-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Customer</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="cutomer-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('customer.index')}}">
                            <i class="bi bi-circle"></i><span>List Customer</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('customer.create')}}">
                            <i class="bi bi-circle"></i><span>Add Customer</span>
                        </a>
                    </li>
                    
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#category-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Category</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="category-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('category.index')}}">
                            <i class="bi bi-circle"></i><span>Categories List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('category.create')}}">
                            <i class="bi bi-circle"></i><span>Add Category</span>
                        </a>
                    </li>
                    
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#subCategory-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Sub Category</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="subCategory-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('sub_category.index')}}">
                            <i class="bi bi-circle"></i><span>Sub Categories List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('sub_category.create')}}">
                            <i class="bi bi-circle"></i><span>Add Sub Category</span>
                        </a>
                    </li>
                    
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="/uncategorized">
                    <i class="bi bi-menu-button-wide"></i><span>Uncategorized</span>
                </a>                
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#productBrand-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Product Brand</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="productBrand-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('product_brand.index')}}">
                            <i class="bi bi-circle"></i><span>List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('product_brand.create')}}">
                            <i class="bi bi-circle"></i><span>Add</span>
                        </a>
                    </li>
                    
                </ul>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#unit-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Unit</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="unit-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('unit.index')}}">
                            <i class="bi bi-circle"></i><span>List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('unit.create')}}">
                            <i class="bi bi-circle"></i><span>Add</span>
                        </a>
                    </li>
                    
                </ul>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#colors-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Colors</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="colors-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('colors.index')}}">
                            <i class="bi bi-circle"></i><span>List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('colors.create')}}">
                            <i class="bi bi-circle"></i><span>Add</span>
                        </a>
                    </li>
                    
                </ul>
            </li> 
            
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#size-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Size</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="size-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('size.index')}}">
                            <i class="bi bi-circle"></i><span>List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('size.create')}}">
                            <i class="bi bi-circle"></i><span>Add</span>
                        </a>
                    </li>
                    
                </ul>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#product-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Product</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="product-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <li>
                        <a href="{{route('product.index')}}">
                            <i class="bi bi-circle"></i><span>List Products</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{route('product.create')}}">
                            <i class="bi bi-circle"></i><span>Add Products</span>
                        </a>
                    </li>  
                    
                </ul>
            </li>
            
            

        </ul>

    </aside><!-- End Sidebar-->

    @yield('content')

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="{{asset('assets/vendor/apexcharts/apexcharts.min.js')}}"></script>
    <script src="{{asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('assets/vendor/chart.js/chart.umd.js')}}"></script>
    <script src="{{asset('assets/vendor/echarts/echarts.min.js')}}"></script>
    <script src="{{asset('assets/vendor/quill/quill.min.js')}}"></script>
    <script src="{{asset('assets/vendor/simple-datatables/simple-datatables.js')}}"></script>
    <script src="{{asset('assets/vendor/tinymce/tinymce.min.js')}}"></script>
    <script src="{{asset('assets/vendor/php-email-form/validate.js')}}"></script>

    <script src="{{asset('assets/js/main.js')}}"></script>

</body>

</html>