routes/web.php
<?php

use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ColorsController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\ProducBrandController;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\UnitController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    
    Route::resource('customer', CustomerController::class);
    Route::get('uncategorized', [CategoryController::class, 'uncategorized']);
    Route::resource('category', CategoryController::class);
    Route::resource('sub_category', SubCategoryController::class);
    Route::resource('product_brand', ProducBrandController::class);
    Route::resource('unit', UnitController::class);
    Route::resource('colors', ColorsController::class);
    Route::resource('size', SizeController::class);
    Route::resource('product', ProductController::class);
    Route::get('get_sub_category', [SubCategoryController::class, 'get_sub_category']);
});

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $table = 'sub_categories';
    protected $primaryKey = 'id';
    protected $fillable = ['name', 'status', 'image', 'category_id'];
    use HasFactory;
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\SubCategory;
use Illuminate\Support\Facades\Storage;


class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = array(
            'page_name' => 'Sub Category',
            'arr' => SubCategory::all(),
        );
        return view('sub_category.index')->with('data' , $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data = array(
            'page_name' => 'Create New Sub Category',
            'arr' => Category::all(),
        );
        
        return view('sub_category.create')->with('data' , $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input = $request->all();        
        request()->validate([
            'name' => 'required|max:20|min:3|regex:/^[A-Za-z_-]/',   
        ]);
        
        if(isset($input['image'])){            
            $file_name = time().$request->file('image')->getClientOriginalName();
            $request->file('image')->storeAs('image/sub_category', $file_name, 'public');
            $input['image'] = $file_name;
        }else{
            $input['image'] = '';
        }

        unset($input['_token']);
        SubCategory::create($input);        
        return redirect('sub_category')->with('flash_message' , "Sub Category Added");
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $data = array(
            'page_name' => 'Sub Category',
            'arr' => SubCategory::find($id),
            'arr_cat' => Category::all(),
        );

        //echo '<pre>';print_r($data['arr']);echo '</pre>';die;

        return view('sub_category.show')->with('data', $data);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $category = SubCategory::find($id);
        $input = $request->all();
        
        if(isset($input['image'])){            
            $file_name = time().$request->file('image')->getClientOriginalName();
            $request->file('image')->storeAs('image/sub_category', $file_name, 'public');
            $input['image'] = $file_name;
            Storage::disk('public')->delete('image/sub_category/' . $input['old_img']);
        }

        

        request()->validate([
            'name' => 'required|max:20|min:3|regex:/^[A-Za-z_-]/',            
        ]);

        unset($input['password']);

        $category->update($input);
        return redirect('sub_category')->with('flash_message', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $SubCategory = SubCategory::find($id);
        Storage::disk('public')->delete('image/sub_category/' . $SubCategory['image']);
        SubCategory::destroy($id);
        return redirect('sub_category')->with('del_message', 'Deleted!');
    }

    public function get_sub_category(Request $request){

        if($request->ajax()){
            $id =  $_GET['category_id'];
            $arr = SubCategory::where('category_id', $id)->get();
            return view('sub_category.get_sub_category', compact('arr'));
        }
        return redirect('dashboard');
    }
}

resources/views/sub_category/create.blade.php
@extends('customer.layout')
@section('content')
<main id="main" class="main">
    <div class="pagetitle">
        <h1><?= $data['page_name']; ?></h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active"><?= $data['page_name']; ?></li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    
    <section class="section dashboard">
        <div class="row">

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Add New</h5>
                        
                        <form class="row g-3" action="{{ route('sub_category.store') }}" method="post" enctype="multipart/form-data">
                            {!! csrf_field() !!}
                            <div class="col-12">
                                <label for="inputNanme4" class="form-label">Name</label>
                                <input type="text" value="{{ old('name') }}" name="name" class="form-control" id="inputNanme4">
                                <b><small class="text-danger">{{ $errors->first('name') }}</small></b>
                            </div>
                            
                            <div class="col-12">
                                <label for="image" class="form-label">Category</label>
                                
                                <select name="category_id" class="form-select" aria-label="Default select example">
                                    @foreach ($data['arr'] as $item)                                    
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-12">
                                <label for="image" class="form-label">Photo</label>
                                <input type="file" name="image" class="form-control" id="inputAddress" placeholder="1234 Main St">
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <button type="reset" class="btn btn-secondary">Reset</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>
    </section>
</main>
@endsection

resources/views/sub_category/get_sub_category.blade.php
<?php
    // echo "<pre>";
    // print_r($arr);
    // echo "</pre>";die;
?>

@foreach ($arr as $v)
    <option value="{{ $v->id }}">{{ $v->name }}</option>
@endforeach

resources/views/sub_category/index.blade.php
@extends('customer.layout')
@section('content')
<main id="main" class="main">

    <div class="pagetitle">
        @if(Session::has('flash_message'))
        <br><br>
        <div class="alert alert-success">
            <h5>{{ Session::get('flash_message') }}</h5>
        </div>
        @endif

        @if(Session::has('del_message'))
        <br><br>
        <div class="alert alert-danger">
            <h5>{{ Session::get('del_message') }}</h5>
        </div>
        @endif
        <h1><?= $data['page_name']; ?></h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active"><?= $data['page_name']; ?></li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">All</h5>

                        <!-- Default Table -->
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Name</th>                                    
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                            @foreach($data['arr'] as $item)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td>{{ $item->name }}</td>                                    
                                    <td>
                                        @if($item->status == 1)
                                            Active
                                        @else
                                            Inactive
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ url('/sub_category/'. $item->id)}}"><button class="btn btn-sm btn-success">View</button></a>
                                        <!-- <a href="{{ url('/customer/'. $item->id .'/edit')}}"><button class="btn btn-sm btn-primary">Edit</button></a> -->
                                        <form method="POST" action="{{ url('/sub_category' . '/' . $item->id) }}" accept-charset="UTF-8" style="display:inline">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Student" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach

                            </tbody>
                        </table>
                        <!-- End Default Table Example -->
                    </div>
                </div>
            </div>

        </div>
    </section>
</main>
@endsection

resources/views/sub_category/show.blade.php
@extends('customer.layout')
@section('content')
<main id="main" class="main">

    <div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Sub Category</li>
          <li class="breadcrumb-item active">View</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                
              <img src="{{ asset('/storage/image/sub_category/'.$data['arr']->image) }}" alt="Profile" class="img-fluid">
                

              <h2>{{ $data['arr']->name }}</h2>              
            </div>
          </div>

        </div>

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  
                  <h5 class="card-title">Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Sub Category Name</div>
                    <div class="col-lg-9 col-md-8">{{ $data['arr']->name }}</div>
                  </div>
                  

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                  <!-- Profile Edit Form -->
                  <form action="{{ url('sub_category/'. $data['arr']->id) }}" method="POST" enctype="multipart/form-data">
                    <div class="row mb-3">
                      <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Change Profile Image</label>
                      <div class="col-md-8 col-lg-9">   

                        <img src="{{ asset('/storage/image/sub_category/'.$data['arr']->image) }}" alt="Profile" class="img-fluid">
                        
                        <div class="pt-2">
                            <input name="image" type="file" class="form-control" id="fullName">
                        </div>
                      </div>
                    </div>

                    {!! csrf_field() !!}
                    {{ method_field('PUT') }}

                    <input type="hidden" name='old_img' value="{{ $data['arr']->image }}">

                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Category</label>
                      <div class="col-md-8 col-lg-9">
                        <select name="category_id" class="form-select" aria-label="Default select example">
                            <option value="0"> Select</option>
                            @foreach ($data['arr_cat'] as $item)                                    
                            <option <?= ($item->id == $data['arr']->category_id)? 'selected' : '';?> value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="name" type="text" class="form-control" id="fullName" value="{{ $data['arr']->name }}">
                        <b><small class="text-danger">{{ $errors->first('name') }}</small></b>
                      </div>
                    </div>
                    

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End Profile Edit Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-settings">

                  <!-- Settings Form -->
                  <form>

                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                      <div class="col-md-8 col-lg-9">
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="changesMade" checked>
                          <label class="form-check-label" for="changesMade">
                            Changes made to your account
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="newProducts" checked>
                          <label class="form-check-label" for="newProducts">
                            Information on new products and services
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="proOffers">
                          <label class="form-check-label" for="proOffers">
                            Marketing and promo offers
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                          <label class="form-check-label" for="securityNotify">
                            Security alerts
                          </label>
                        </div>
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End settings Form -->

                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>
  </main>
  @endsection